os: linux
sudo: required
language: "minimal"
services:
  - docker
 
 
 
jobs:
  include:
    script:
    - docker build . --tag dockergosha
    - docker run -it -v `pwd`:`pwd` -w `pwd` dockergosha ./scripts/compile.sh
 
notifications:
  email: false
